import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams } from "react-router-dom";
import { specialties, specialtyTexts as t } from "../../data/specialties";
import styles from "./SpecialtyPage.module.css";
export default function SpecialtyPage() {
    const { slug } = useParams();
    const specialty = specialties.find(s => s.slug === slug);
    if (!specialty)
        return _jsx("div", { className: "text-center mt-10 text-xl", children: t.notFound });
    return (_jsxs("div", { className: styles.container, children: [_jsx("h1", { className: styles.title, children: specialty.title }), _jsxs("p", { className: styles.degree, children: ["(", specialty.degree, ")"] }), _jsxs("div", { className: styles.gridInfo, children: [_jsxs("p", { children: [_jsx("strong", { children: t.minScore }), " ", specialty.minBudgetScore2023] }), _jsxs("p", { children: [_jsx("strong", { children: t.budgetPlaces }), " ", specialty.budgetPlaces] }), _jsxs("p", { children: [_jsx("strong", { children: t.totalPlaces }), " ", specialty.totalPlaces] }), _jsxs("p", { children: [_jsx("strong", { children: t.fullTimeCost }), " ", specialty.costFullTime] }), _jsxs("p", { children: [_jsx("strong", { children: t.partTimeCost }), " ", specialty.costPartTime] })] }), _jsx("p", { className: styles.description, children: specialty.description }), _jsxs("div", { children: [_jsx("h2", { className: styles.sectionTitle, children: t.programTitle }), _jsx("ul", { className: styles.list, children: specialty.programs.map((item, i) => _jsx("li", { children: item }, i)) })] }), _jsxs("div", { children: [_jsx("h2", { className: styles.sectionTitle, children: t.careersTitle }), _jsx("div", { className: "grid md:grid-cols-2 gap-4", children: specialty.careers.map((career, i) => (_jsxs("div", { className: styles.careerCard, children: [_jsx("h3", { className: styles.careerTitle, children: career.title }), _jsx("p", { className: styles.salary, children: career.salary }), _jsx("p", { children: career.description })] }, i))) })] }), _jsxs("div", { children: [_jsx("h2", { className: styles.sectionTitle, children: t.alumniTitle }), _jsx("div", { className: "grid sm:grid-cols-2 gap-4", children: specialty.alumni.map((alumnus, i) => (_jsxs("div", { className: styles.alumniCard, children: [_jsx("strong", { children: alumnus.name }), _jsx("br", {}), alumnus.role, " \u0443 ", _jsx("em", { children: alumnus.company })] }, i))) })] })] }));
}
